{
    'name': 'Procesa Datos',
    'version': '1.1',
    'category': '',
    'sequence': 6,
    'license': 'LGPL-3',
    'summary': '',
    'description': """
        """,
    'author': "JIC",
    'website': '',
    'depends': ['base','mail'],
    'data': [
        'security/ir.model.access.csv',
        'views/views.xml',
        'wizard/data_import_view.xml',
        'views/process_group.xml',
        'views/process_data.xml',
        'views/process_jp.xml',
        'views/process_proyecto.xml',
        'views/process_ticket.xml',
        'views/process_ticket_categ.xml',
        'views/process_feriado.xml',

#        'data/cron.xml',
#        'data/report_paperformat_data.xml',
#        'data/mail_template_data.xml',
#        'views/res_config_settings_views.xml',
#        'views/views.xml',
#        'views/report_invoice.xml',
#        'views/stock_picking_view.xml',
#        'views/report_delivery_guide.xml',
    ],
    'installable': True,
    'license': 'LGPL-3',
}
